[package]
name = "gallery_derive"
version = "0.1.0"
authors = ["Gaël Berthaud-Müller <blacksponge@tuta.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = [ "extra-traits" ] }
quote = "0.6.11"
proc-macro2 = "0.4.27"
